# This is going to be equivalent to  
#    $  docker volume create crv_mysql
#    $ docker run -d --rm --name=database -e MYSQL_USER=dbuser -e MYSQL_DATABASE=wordpress -e
#    MYSQL_PASSWORD=dbpass -e MYSQL_ROOT_PASSWORD=root --mount
#    type=volume,src=crv_mysql,dst=/var/lib/mysql -p 3306:3306 --rm -d mysql:5.7 mysqld --innodb-buffer-pool-side=64M
---
- name: create volume for the mysql container
  docker_volume:
    name: crv_mysql
    
- name: start docker container (mysql)  
  docker_container:
    name: dataside
    image: mysql:5.7
    ports:
    - 3306:3306
    restart: yes
    env:
        MYSQL_ROOT_PASSWORD=root
        MYSQL_DATABASE=wordpress
        MYSQL_USER=dbuser
        MYSQL_PASSWORD=dbpass       
    state: started
    volumes:
      - "crv_mysql:/var/lib/mysql"      
    command: ['myslqd','--innodb-buffer-pool-side=64M']
