---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install docker dependencies
  apt: name={{ item }}  state=present  #one way to loop
  with_items:                          #through a list of items
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools

- name: Add docker's key to the repo 
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

#DEPRECATED
# - name: Update apt and install docker
#   apt: name={{ item }} state=latest update_cache=yes #another way to loop 
#   loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io'] #through a list 
- name: Update apt and install docker
  apt: name={{ item }} state=latest update_cache=yes #another way to loop 
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install docker module for python
  pip:
    name: docker 
      
- name: Start docker
  service:
    name: docker
    state: started
